### ISSUE TITLE
Dockerization - Plotting

### ISSUE THREAD

**Issue by N2ITN** [Data4Democracy/are-you-fake-news#17]
## Status
Assigning to @ivyleavedtoadflax 
Please use the https://github.com/N2ITN/are-you-fake-news/tree/develop-dockerize branch.

### Issue
Adapt the plotting function to a standalone docker service. It should maintain the same input json of bias scores and save the rendered images to a shared volume using a standardized name. This is mainly a repackaging and should not change the existing code in huge ways.

### Tasks
Create dockerfile under `./docker/plotter/`

- [x]  Wrap the existing plotting code in a simple flask API that accepts POST requests with the existing input format.
- [x]  Change the image path to save to a local volume rather than S3
- [x]  Add the plotter dockerfile to the configuration in docker-compose.yaml
- [ ]  Write unit tests for the basic use case, these can be expanded later.

**Comment by ivyleavedtoadflax** [comment]
On it 👍
