### ISSUE TITLE
Dockerization - docker-compose

### ISSUE THREAD

**Issue by N2ITN** [Data4Democracy/are-you-fake-news#22]
## Status
Assigning to @
Refers to this branch https://github.com/N2ITN/are-you-fake-news/tree/develop-dockerize

### Issue
As new microservices are added to the app, the docker-compose files will evolve.
As of the time of writing this issue, issuing the commands `docker compose build && docker compose up` from the `./docker/` directory will start up a web app, mongo instance, and prediction service.

There are plans to add a persistent volume for rendered plot images, and web scraping services.

Additionally a new docker-compose file for data collection and model training will need to be created, as per https://github.com/Data4Democracy/are-you-fake-news/issues/19 &  https://github.com/Data4Democracy/are-you-fake-news/issues/20.
This is an ongoing effort that will be central to coordinating the integrity of the app services.

### Tasks
- [x] Create web facing docker-compose
- [x]  Maintain and debug the web facing docker-compose.yaml
- [ ]  As new pull requests are approved, ensure the integrity and stability of the docker-compose
- [ ]  Assist with the second docker-compose that will boot the data collection / model training services.
