### ISSUE TITLE
Dockerization - Web Interface [WIP]

### ISSUE THREAD

**Issue by N2ITN** [Data4Democracy/are-you-fake-news#23]
## Status
Assigning to @N2ITN 
Refers to branch https://github.com/N2ITN/are-you-fake-news/tree/develop-dockerize
### Issue
Dockerize the flask web interface for the project
### Tasks

- [x] Create a dockerfile for `./docker/web/`
- [x] Add to docker-compose
- [ ] Create unit tests
