### ISSUE TITLE
Dockerization - MongoDB

### ISSUE THREAD

**Issue by N2ITN** [Data4Democracy/are-you-fake-news#24]
## Status
Assigning to @N2ITN 
Refers to this branch https://github.com/N2ITN/are-you-fake-news/tree/develop-dockerize

### Issue
Create project-wide persistent mongodb docker configuration and add to docker-compose.
This will be used for live web scraping, as well as storing predictions.
On the backend this will be used for scraping training data.

### Tasks
- [x] Create mongodb dockerfile
- [x]  Add mongodb to web-facing docker-compose with persistent volume
- [x]  Add mongodb to data collection / model training docker-compose with persistent volume

**Comment by N2ITN** [comment]
Done
