### ISSUE TITLE
Website frontend - Call for web dev, data visualization

### ISSUE THREAD

**Issue by N2ITN** [Data4Democracy/are-you-fake-news#27]
## Status
Assigning to [unassigned]. Multiple contributors welcome.
Refers to branch https://github.com/N2ITN/are-you-fake-news/tree/develop-dockerize
### Issue
The front end code in `./web` could use some improving.
It's written in flask and uses bootstrap templates but is not very sophisticate. Front end developers this is your time to shine!

 A few possible areas for improvement:

- Only two pages. A separate "about" page would be nice. Or a blog. Something to give information about the project, how it relates to data for democracy, some guide for how people can contribute etc 

- For data visualization folks, there is a lot of opportunity to display the collected predictions in interesting and novel ways. Go nuts! The plots are currently doing an okay job, but it doesn't have to stop there.
- Makeover. While the site looks pretty cool, it's quite basic and fancier designs are welcome.

Most of the areas for improvement are contained in `./docker/web/app.py` but also `.docker/web/static/` where the html and css are stored. The data is stored in mongo which starts up with `docker-compose up`. For those wanting to do data visualization, run the website a few news sites first to get 

### Tasks

- [ ] Add an about or blog page 
- [ ] Find new ways to visualize the data. This could be interactive D3 plots, new charts, comparing different websites etc. Get creative!
- [ ] Any other improvements to design or presentation.
