### ISSUE TITLE
Web Backend - Link to Domain Analysis

### ISSUE THREAD

**Issue by N2ITN** [Data4Democracy/are-you-fake-news#28]
## Status
Assigning to Sophia C
Refers to branch https://github.com/N2ITN/are-you-fake-news/tree/develop-dockerize
### Issue

Linking to a specific site's analysis should be enabled for sharing purposes.

Example:
areyoufakenews.com/analysis/cnn-dot-com (or some character substitution for dots) should link to existing analysis, or run the analysis if it hasn't been run.

### Tasks

- [ ] Find a URL scheme to link websites that supports subdomains (motherboard.vice.com) using character substitution.
- [ ] Implement and test
- [ ] Option but awesome: add "Link to this page" text to results page.
